Allow virtual hosts to be disabled. Support certificate lookups.

diff --git a/device-httpd-el9/src/main/resources/usr/libexec/device-httpd-autodiscovery-virtualhost b/device-httpd-el9/src/main/resources/usr/libexec/device-httpd-autodiscovery-virtualhost
--- a/device-httpd-el9/src/main/resources/usr/libexec/device-httpd-autodiscovery-virtualhost
+++ b/device-httpd-el9/src/main/resources/usr/libexec/device-httpd-autodiscovery-virtualhost
@@ -1,12 +1,85 @@
 #!/bin/bash
 
-
 #
-# Create instance that does not yet exist
-create_instance() {
+# Per application? Run all scripts
+
+run_scripts() {
+
   instance="${1}"
   virtualhost="${2}"
   line="${3}"
+
+  logger -t "httpd-autodiscovery@${instance}" "generating virtualhosts for httpd instance ${instance}..."
+
+  rm -f "${line}/warning"
+
+  find "/usr/libexec/device-httpd-autodiscovery-virtualhost.d" -type f -executable | sort | \
+  while read x; do
+    "$x" "${instance}" "${virtualhost}" "${line}" < /dev/null || touch error;
+  done
+
+  if test ! -f "error"; then
+    logger -t "httpd-autodiscovery@${instance}" "completed virtualhosts for httpd instance ${instance}."
+  else
+    logger -t "httpd-autodiscovery@${instance}" "failed virtualhosts for httpd instance ${instance}."
+  fi
+
+}
+
+
+#
+# Enable instance that does not yet exist
+enable_instance() {
+  instance="${1}"
+  virtualhost="${2}"
+  line="${3}"
+
+  if test -f "${line}/listen.d/address.txt"; then
+    address="$(head ${line}/listen.d/address.txt)"
+  else
+    address="*"
+  fi
+
+  if test -f "${line}/listen.d/port.txt"; then
+    listen="${address}:$(head -n 1 ${line}/listen.d/port.txt)"
+  fi
+  if test -f "${line}/listen.d/tls-port.txt"; then
+    tlslisten="${address}:$(head -n 1 ${line}/listen.d/tls-port.txt)"
+  fi
+
+  if test -f "$line/server-name.txt"; then
+    servername=$(head -n 1 $line/server-name.txt)
+  else
+    servername=$(hostname -f)
+  fi
+
+  if test -n "${tlslisten}"; then
+
+    install -m 750 -d "/run/httpd/device-${instance}"
+
+    logger -t httpd-autodiscovery@${instance} "importing httpd server certificate/key..."
+
+    redwax-tool --pem-in="/etc/pki/tls/private/*" \
+                --pem-in="/etc/pki/tls/certs/ca-bundle.trust.crt" \
+                --pem-in="/etc/pki/tls/certs/*.pem" \
+                --filter=verify \
+                --filter-hostname="${servername}" \
+                --filter-current \
+                --cert-out --chain-out --no-key-out \
+                --pem-out="/run/httpd/device-${instance}/${virtualhost}.crt" \
+                --no-cert-out --no-chain-out --key-out \
+                --pem-out="/run/httpd/device-${instance}/${virtualhost}.key" || echo "Could not import cert/key for tls" > "${line}/error"
+
+    if test ! -f "${line}/error"; then
+      logger -t httpd-autodiscovery@${instance} "imported httpd server certificate/key for ${servername}."
+    else
+      logger -t httpd-autodiscovery@${instance} "failed to import httpd server certificate/key for ${servername}. Skipping virtualhost."
+
+      # give up and skip virtual host creation
+      return
+    fi
+
+  fi
 
   cat >> "secure-${virtualhost}.conf" <<- EOF
 # Generated by $0 on `date`
@@ -22,25 +95,15 @@ EOF
 
 EOF
 
-  if test -f "${line}/listen.d/address.txt"; then
-    address="$(head ${line}/listen.d/address.txt)"
-  else
-    address="*"
-  fi
-
-  if test -f "${line}/listen.d/port.txt"; then
-    listen="${address}:$(head -n 1 ${line}/listen.d/port.txt)"
-  fi
-  if test -f "${line}/listen.d/tls-port.txt"; then
-    tlslisten="${address}:$(head -n 1 ${line}/listen.d/tls-port.txt)"
-  fi
-
-  if test -f "${line}/server-name.txt"; then
-    servername="$(head -n 1 ${line}/server-name.txt)"
-  fi
-
+  #
+  # Handle secure host
   if test -n "${tlslisten}"; then
+
     cat >> "secure-${virtualhost}.conf" <<- EOF
+<IfModule !ssl_module>
+  LoadModule ssl_module modules/mod_ssl.so
+</IfModule>
+
 #
 # Secure virtual host
 <VirtualHost ${tlslisten}>
@@ -50,10 +113,15 @@ EOF
     if test -n "${servername}"; then
       cat >> "secure-${virtualhost}.conf" <<- EOF
   ServerName ${servername}
+
 EOF
     fi
 
     cat >> "secure-${virtualhost}.conf" <<- EOF
+  SSLEngine on
+  SSLCertificateFile /run/httpd/device-${instance}/${virtualhost}.crt
+  SSLCertificateKeyFile /run/httpd/device-${instance}/${virtualhost}.key
+
   IncludeOptional /etc/httpd/conf.d/device-${instance}/secure-${virtualhost}.d/*.conf
 </VirtualHost>
 EOF
@@ -83,12 +151,14 @@ EOF
   install -m 640 "secure-${virtualhost}.conf" "/etc/httpd/conf.d/device-${instance}/secure-${virtualhost}.conf"
   install -d 0750 "/etc/httpd/conf.d/device-${instance}/virtual-${virtualhost}.d/"
   install -d 0750 "/etc/httpd/conf.d/device-${instance}/secure-${virtualhost}.d/"
+
+  run_scripts "${instance}" "${virtualhost}" "${line}"
 }
 
 
 #
-# Remove existing virtualhost
-remove_instance() {
+# Disable existing virtualhost
+disable_instance() {
   instance="${1}"
   virtualhost="${2}"
 
@@ -98,32 +168,6 @@ remove_instance() {
   rm -rf "/etc/httpd/conf.d/device-${instance}/secure-${virtualhost}.d/"
 }
 
-
-#
-# Per application? Run all scripts
-
-run_scripts() {
-
-  instance="${1}"
-  virtualhost="${2}"
-  line="${3}"
-
-  logger -t "httpd-autodiscovery@${instance}" "generating virtualhosts for httpd instance ${instance}..."
-
-  rm -f "${line}/warning"
-
-  find "/usr/libexec/device-httpd-autodiscovery.d/virtualhost.d" -type f -executable | sort | \
-  while read x; do
-    "$x" "${instance}" "${virtualhost}" "${line}" < /dev/null || touch error;
-  done
-
-  if test ! -f "error"; then
-    logger -t "httpd-autodiscovery@${instance}" "completed virtualhosts for httpd instance ${instance}."
-  else
-    logger -t "httpd-autodiscovery@${instance}" "failed virtualhosts for httpd instance ${instance}."
-  fi
-
-}
 
 if [ $# -eq 2 ]; then
 
@@ -151,7 +195,7 @@ if [ $# -eq 2 ]; then
     if test -f "$line/removed"; then
 
       logger -t httpd-autodiscovery "removing virtualhost from httpd server instance ${instance}..."
-      remove_instance "${instance}" "${virtualhost}"
+      disable_instance "${instance}" "${virtualhost}"
       logger -t httpd-autodiscovery "removed virtualhost from httpd server instance ${instance}."
 
       # remove folder
@@ -159,42 +203,28 @@ if [ $# -eq 2 ]; then
       rmdir "${target}"
       rm -f "${line}"
 
-    # add new instances
-    elif test -f "$line/added"; then
+    # update to disabled state
+    elif test -f "$line/disabled.bin"; then
 
-      # instance already exist and we're told to add? none of our business, remove the device config for safety
-      if test -d "/etc/httpd/conf.d/device-${instance}/virtualhost-${virtualhost}.d/"; then
-
-        logger -t httpd-autodiscovery "'"/etc/httpd/conf.d/device-${instance}/virtualhost-${virtualhost}.d/"' already exists, ignoring '$line'"
-        echo "Virtualhost ${virtualhost} already exists" > ${line}/error
-
-        continue;
-      fi
-
-      logger -t httpd-autodiscovery "creating virtualhost in httpd server instance ${instance}..."
-      create_instance "${instance}" "${virtualhost}" "${line}"
-      run_scripts "${instance}" "${virtualhost}" "${line}"
-      logger -t httpd-autodiscovery "created virtualhost in httpd server instance ${instance}."
+      logger -t httpd-autodiscovery "disabling virtualhost from httpd server instance ${instance}..."
+      disable_instance "${instance}" "${virtualhost}"
+      logger -t httpd-autodiscovery "disabled virtualhost from httpd server instance ${instance}."
 
       rm -f "$line/added"
 
-    # update instances
-    elif test -f "$line/updated"; then
-
-      run_scripts "${instance}" "${virtualhost}" "${line}"
-
-      rm -f "$line/updated"
-
-    # something we depend on changed
+    # update to enabled state
     else
 
+      logger -t httpd-autodiscovery "creating virtualhost in httpd server instance ${instance}..."
+      enable_instance "${instance}" "${virtualhost}" "${line}"
       run_scripts "${instance}" "${virtualhost}" "${line}"
+      logger -t httpd-autodiscovery "created virtualhost in httpd server instance ${instance}."
+
+      rm -f "$line/updated"
 
     fi
 
   done < <(find /etc/device/services/www/virtualhost/ -mindepth 1 -maxdepth 1 -type l)
-
-#  install -m 640 "device-${instance}-listen.conf" "/etc/httpd/conf.d/device-${instance}"/listen.conf
 
 fi
 
